# Generated by Django 3.1.1 on 2020-10-11 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData',
            new_name='Regs',
        ),
    ]
