# Generated by Django 3.1.1 on 2020-10-11 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20201011_1232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regs',
            new_name='UserData',
        ),
    ]
