# Generated by Django 3.1.1 on 2020-10-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20201011_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClgId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_name', models.CharField(max_length=6)),
            ],
        ),
    ]
