# Generated by Django 3.1.1 on 2020-10-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_clgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clgid',
            name='clg_name',
            field=models.CharField(choices=[('#', 'Default'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], max_length=6),
        ),
    ]
