# Generated by Django 3.1.1 on 2020-10-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_auto_20201012_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clgid',
            name='clg_name',
            field=models.CharField(choices=[('1', ' Bharti Vidyapeeth Institute of Management and Information Technology, Belapur .'), ('2', "Chikitsak Samuha's S. S. & L. S. Patkar College, Goregoan."), ('3', 'N. G. Acharya & D. K. Marathe College of Arts, Science & Commerce, Chembur.'), ('4', 'Karmaveer Bhaurao Patil College, Vashi.'), ('5', "S. P. N. Doshi Women's College,Ghatkopar.")], max_length=6),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='clg_name',
            field=models.CharField(choices=[('1', ' Bharti Vidyapeeth Institute of Management and Information Technology, Belapur.'), ('2', "Chikitsak Samuha's S. S. & L. S. Patkar College, Goregoan."), ('3', 'N. G. Acharya & D. K. Marathe College of Arts, Science & Commerce, Chembur.'), ('4', 'Karmaveer Bhaurao Patil College, Vashi.'), ('5', "S. P. N. Doshi Women's College,Ghatkopar.")], max_length=6),
        ),
    ]
